import {
    Body,
    Button,
    Container,
    Head,
    Heading,
    Html,
    Link,
    Preview,
    Section,
    Text,
    Tailwind,
    Hr,
} from "@react-email/components";
import * as React from "react";

interface PracticeAuditEmailProps {
    reportId: string;
    adminHours: number;
    totalLeak: number;
    city?: string;
}

export const PracticeAuditEmail = ({
    reportId,
    adminHours,
    totalLeak,
    city = "Your Practice",
}: PracticeAuditEmailProps) => {
    const previewText = `Your Practice Efficiency Audit is Ready`;
    // Ensure we have a valid reportId before constructing the URL
    const reportUrl = reportId ? `https://virtualminds.ai/tools/practice-leaks/report/${reportId}` : "https://virtualminds.ai";

    return (
        <Html>
            <Head />
            <Preview>{previewText}</Preview>
            <Tailwind
                config={{
                    theme: {
                        extend: {
                            colors: {
                                primary: "#D2691E",
                                navy: "#0A192F",
                            },
                        },
                    },
                }}
            >
                <Body className="bg-slate-100 font-sans my-auto mx-auto px-2">
                    <Container className="border border-solid border-[#eaeaea] rounded my-[40px] mx-auto p-[20px] max-w-[465px] bg-white">
                        <Section className="mt-[32px]">
                            <Text className="text-xs font-bold text-primary tracking-widest uppercase mb-2 text-center">Virtual Minds</Text>
                            <Heading className="text-2xl font-serif font-bold text-center text-navy p-0 my-0 mx-0">
                                Audit Complete
                            </Heading>
                        </Section>

                        <Section className="p-6 mt-8 mb-8 bg-slate-50 rounded-lg border border-slate-100 text-center">
                            <Text className="text-slate-500 text-sm uppercase font-bold tracking-wider mb-2">Total Projected Leak</Text>
                            <Text className="text-4xl font-serif font-bold text-primary my-0">
                                {new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(totalLeak)}/yr
                            </Text>
                            <Text className="text-xs text-red-500 font-bold mt-2">
                                CRITICAL LOAD DETECTED
                            </Text>
                        </Section>

                        <Text className="text-slate-700 text-[14px] leading-[24px]">
                            We have analyzed your inputs for <strong>{city}</strong>. Based on your reported <strong>{adminHours} hours/week</strong> of administrative load, significant revenue is being diverted from clinical care.
                        </Text>

                        <Text className="text-slate-700 text-[14px] leading-[24px]">
                            Your full confidential report is ready. It details:
                        </Text>

                        <Section>
                            <ul className="text-slate-700 text-[14px] leading-[24px] pl-4">
                                <li className="mb-2">The exact breakdown of your "Admin Drag"</li>
                                <li className="mb-2">Your "Growth Gap" revenue potential</li>
                                <li className="mb-2">A customized recovery plan</li>
                            </ul>
                        </Section>

                        <Section className="text-center mt-[32px] mb-[32px]">
                            <Button
                                className="bg-[#D2691E] text-white px-8 py-4 rounded-lg font-bold text-[14px] no-underline"
                                href={reportUrl}
                            >
                                View Full Report
                            </Button>
                        </Section>

                        <Hr className="border border-solid border-[#eaeaea] my-[26px] mx-0 w-full" />

                        <Text className="text-[#666666] text-[12px] leading-[24px] text-center">
                            This audit was generated by Virtual Minds AI. <br />
                            Confidentiality Guaranteed.
                        </Text>
                    </Container>
                </Body>
            </Tailwind>
        </Html>
    );
};

export default PracticeAuditEmail;
